### ISSUE TITLE
Png Converter Error Line 51 Call to undefined function imagecreatefromppng()/Other

### ISSUE THREAD

**Issue by Eradok** [leikareipa/retro-ngon#1]
![error](https://user-images.githubusercontent.com/89960134/133319908-b669a5fd-03fa-49b7-8f42-872ddcafb43c.PNG)

Hi I love your engine im gonna try and make a game out of it so ive been studying how it works and icking it aapart
but when i got to the texture data representation i cant decode it, I copy te data into an online Base64 decoder and its giberish out the other side, so i wanted to try and encode an image at least and decode it the hard way but i cant  seem to get the php script to run, are there any other file formats and or data formats to represent the texture and any tips on how to go about that, Thank YOU!, Would it be difficult to implement some form of culling to drop the polygon count in more complex scenes.

**Comment by leikareipa** [comment]
Sounds cool, let me know how it goes.

The converter may need PHP's GD package.

I think textures can have their pixel data either Base64 encoded (16-bit packed pixels, RGBA/5551) or as a plain array of 8-bit values (0-255, RGBA), and in the latter case the "encoding" attribute would be "none" and the "channels" attribute would be "rgba:8+8+8+8".

Right now the renderer only has back-face culling, so other kinds of culling (including mesh LOD) is up to the user.

**Comment by Eradok** [comment]
Thank you, it was the gd packkage and i had to use xampps php to edit the php.ini.
Now that its running i get the error from that func
![ERROR2](https://user-images.githubusercontent.com/89960134/133377206-f409d0ab-56b4-46a4-8401-79fee24399b0.PNG)

**Comment by Eradok** [comment]
How would i go about decoding the image, Or do you have any tips for editing the pixel data from ingame to paint on the meshes

**Comment by Eradok** [comment]
How to i cull the polygons hidden by other scenery, How would i implemet it in the demos, becouse the poly count doesnt drop when i go behind a pillar in the first person example, or others that ive seen am i just missing it?,

**Comment by leikareipa** [comment]
It's possible the error is due to a missing source PNG file. I think the png2json.php file has instructions for the command-line options, but basically it takes in an existing PNG and outputs a JSON file.

The pixels in the Base64 encoded data are 16-bit integers that hold 5 bits of red, green and blue, and 1 bit of alpha. The 16-bit values by themselves look random but if you mask out e.g. the first (or last, I forget) 5 bits of a given 16-bit value then you'll get the value of the first color channel, etc., and you'd then shift that up from 5 bits to 8 bits to get the color value in the usual 0-255 range.

The renderer isn't meant to be a full-blown 3d engine at the moment, so the culling just has to be done using other methods. You'd use whatever method to determine which regions are visible and then only submit those polygons to be rendered.

**Comment by Eradok** [comment]
hi sorry for not getting back sooner, i cant seem to be able to input the file location propely becouse i get file doesnt exist error, I have the test.png in the same folder, its a 16x16 and im using "php png2jason.php -i (test.png)" and ive tried full path dirname realpath ../ ..\ with the end bit of [-o(whatever)] and without just changes the name so im stumped not sure how to proceed

**Comment by leikareipa** [comment]
You could try modifying the png2json.php file by adding `echo $commandLine["i"], PHP_EOL;` at line 50, then running the script as you have now. It should print into the console the name of the file it's trying to open. If the name seems correct then at least that's working.

It may be that the PNG image is in an unsupported format. I can't remember for sure, but it's possible the image needs to be in 32 bit color, i.e. with an alpha channel.
